version: '3.6'

services:

#groupadd -g 999 docker

#https://github.com/jakubhajek/elasticsearch-docker-swarm/blob/master/stack-elastic.yml
# elasticsearch coordinating node
# /etc/security/limits.conf
# * hard memlock unlimited
# * soft memlock unlimited
# * hard nofile 65536
# * soft nofile 65536
# * hard nproc 65536
# * soft nproc 65536

#vim /etc/rc.local
#echo never > /sys/kernel/mm/transparent_hugepage/enabled
#exit 0

#/etc/sysctl.conf
#vm.max_map_count=262144
#vm.overcommit_memory=1
#net.core.somaxconn=1024

#/lib/systemd/system/docker.service
#/usr/lib/systemd/system/elasticsearch.service
#LimitMEMLOCK=infinity

#apt update
#apt install apt-transport-https ca-certificates curl software-properties-common
#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

#add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
#apt update

#apt-cache policy docker-ce
#apt install docker-ce=18.06.3~ce~3-0~ubuntu
#apt-get install nfs-common

#docker swarm join-token worker
#docker swarm join --token SWMTKN-1-1fd9zytidyai9bfelii0vt5nee6l43ibedvwjztbgncxfil2oi-0ungbwdty6jaihk5g7usk5pv9 192.168.25.46:2377

#sudo adduser allinone --disabled-password
#sudo usermod -aG sudo allinone

  es-master-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-master-01
    volumes:
      - type: volume
        source: es-master-01
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      cluster.name: es-swarm-cluster
      node.name: "es-master-01"
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.master: "true"
      node.voting_only: "false"
      node.data: "false"
      node.ingest: "false"
      node.ml: "false"
      xpack.ml.enabled: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-data-01
      - es-data-02
    configs: &es-limits-conf
      - source: es-limits.conf
        target: /etc/security/limits.conf
    networks: &allinone-network
      - allinoneNetwork
    deploy: &allinone-master-deploy
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s1]
    logging: &allinone-logging
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  es-master-02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-master-02
    volumes:
      - type: volume
        source: es-master-02
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      cluster.name: es-swarm-cluster
      node.name: "es-master-02"
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.master: "true"
      node.voting_only: "false"
      node.data: "false"
      node.ingest: "false"
      node.ml: "false"
      xpack.ml.enabled: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-data-01
      - es-data-02
    configs: *es-limits-conf
    networks: *allinone-network
    deploy: 
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s2]
    logging: *allinone-logging

  es-master-03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-master-03
    volumes:
      - type: volume
        source: es-master-03
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      cluster.name: es-swarm-cluster
      node.name: "es-master-03"
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.master: "true"
      node.voting_only: "false"
      node.data: "false"
      node.ingest: "false"
      node.ml: "false"
      xpack.ml.enabled: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-data-01
      - es-data-02
    configs: *es-limits-conf
    networks: *allinone-network
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s3]
    logging: *allinone-logging

  es-data-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-data-01
    volumes:
      - type: volume
        source: es-data-01
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      cluster.name: es-swarm-cluster
      node.name: "es-data-01"
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.master: "false"
      node.voting_only: "false"
      node.data: "true"
      node.ingest: "false"
      node.ml: "false"
      xpack.ml.enabled: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    configs: *es-limits-conf
    networks: *allinone-network
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s1]
    logging: *allinone-logging

  es-data-02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-data-02
    volumes:
      - type: volume
        source: es-data-02
        target: /usr/share/elasticsearch/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      cluster.name: es-swarm-cluster
      node.name: "es-data-02"
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.master: "false"
      node.voting_only: "false"
      node.data: "true"
      node.ingest: "false"
      node.ml: "false"
      xpack.ml.enabled: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    configs: *es-limits-conf
    networks: *allinone-network
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s2]
    logging: *allinone-logging

  es-ingest:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-ingest
    volumes: &allinone-volume
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      cluster.name: es-swarm-cluster
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.name: "es-ingest"
      node.master: "false"
      node.voting_only: "false"
      node.data: "false"
      node.ingest: "true"
      node.ml: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
      xpack.monitoring.collection.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master-01
      - es-master-02
      - es-master-03
    configs: *es-limits-conf
    networks: *allinone-network
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s3]
    logging: *allinone-logging

  es-coordinating:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELKVERSION:-7.17.4}
    hostname: es-coordinating
    #ports:
    #  - 9200:9200
    #  - 9300:9300
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    volumes: &allinone-volume
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      network.host: 0.0.0.0
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      cluster.name: es-swarm-cluster
      discovery.seed_hosts: "es-master-01,es-master-02,es-master-03"
      cluster.initial_master_nodes: "es-master-01,es-master-02,es-master-03"
      node.name: "es-coordinating"
      node.master: "false"
      node.voting_only: "false"
      node.data: "false"
      node.ingest: "false"
      node.ml: "false"
      cluster.remote.connect: "false"
      MAX_LOCKED_MEMORY: unlimited
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es-master-01
      - es-master-02
      - es-master-03
    configs: *es-limits-conf
    networks: *allinone-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s1]
    logging: *allinone-logging

  elastichq:
    image: elastichq/elasticsearch-hq
    environment:
      - HQ_DEFAULT_URL=http://es-coordinating:9200
      - HQ_DEBUG=True
      - HQ_ENABLE_SSL=False
      - HQ_VERIFY_CERTS=False
    ports:
      - 5050:5000
    volumes: *allinone-volume
    networks: *allinone-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s2]
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
        tag: elastichq

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELKVERSION:-7.17.4}
    hostname: kibana
    ports:
      - 5601:5601
    volumes:
      - kibanaconf:/usr/share/kibana/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "ELASTICSEARCH_URL=http://es-coordinating:9200"
      - "ELASTICSEARCH_HOSTS=http://es-coordinating:9200"
    depends_on:
      - es-coordinating
    networks: *allinone-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s3]
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
        tag: kibana

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELKVERSION:-7.17.4}
    ports:
      - "5000:5000"
      - "9600:9600"
      - "5044:5044"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    depends_on:
      - kibana
    volumes: *allinone-volume
    networks: *allinone-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s1]
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
        tag: logstash

  apm-server:
    image: docker.elastic.co/apm/apm-server:${ELKVERSION:-7.17.4}
    ports:
      - "8200:8200"
    configs:
      - source: apmserver.conf
        target: /usr/share/apm-server/apm-server.yml
    volumes: *allinone-volume
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s2]
    networks: *allinone-network
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        fluentd-async-connect: "true"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
        tag: apmserver

  fluentd:
    image: 313.co.kr:5550/313devgrp/fluentd:3.1.3
    ports:
      - 24224:24224
      - 24224:24224/udp
    configs:
      - source: fluentd.conf
        target: /fluentd/etc/fluent.conf
    volumes: *allinone-volume
    extra_hosts: &app-addhost
      - "313.co.kr:192.168.25.46"
      - "db.313.co.kr:192.168.25.40"
      - "nas.313.co.kr:192.168.25.42"
      - "www.313.co.kr:192.168.25.42"
      - "ubuntu.313.co.kr:192.168.25.46"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == k8s2]
    networks: *allinone-network
    logging: *allinone-logging

configs:
  fluentd.conf:
    file: ./allinone/fluent.conf
  apmserver.conf:
    file: ./allinone/apm-server.yml
  es-limits.conf:
    file: ./allinone/es-limits.conf
  logstash_config:
    file: ./allinone/logstash.yml
  logstash_pipeline:
    file: ./allinone/logstash.conf

volumes:

  kibanaconf:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/allinone/kibana/conf"

  es-master-01:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/allinone/es-master-01"

  es-master-02:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/allinone/es-master-02"

  es-master-03:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/allinone/es-master-03"

  es-data-01:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/allinone/es-data-01"

  es-data-02:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFSSERVER:-1.2.3.4},nolock,soft,rw,sync"
      device: ":${NFSPATH:-/nfspath}/allinone/es-data-02"

networks:
  allinoneNetwork:
    driver: overlay
    attachable: true
