apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-storage-claim
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 64Gi
  selector:
#    matchLabels:
#      type: nfs
   matchExpressions:
      - key: type
        operator: In
        values:
          - nfs
